// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk8qa0czd0vYTER7ZJ_Bq8gU_eBFgVHJY',
    appId: '1:528108806700:web:0e5214306378081f69e789',
    messagingSenderId: '528108806700',
    projectId: 'sale-app-cf077',
    authDomain: 'sale-app-cf077.firebaseapp.com',
    storageBucket: 'sale-app-cf077.firebasestorage.app',
    measurementId: 'G-BQPNHBY49E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKiG8NpdILsKqa_-i0_xjH6uL6LUHa8Gw',
    appId: '1:528108806700:android:cf87a48f13137bca69e789',
    messagingSenderId: '528108806700',
    projectId: 'sale-app-cf077',
    storageBucket: 'sale-app-cf077.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjrkWtBY4U_9sgJK5zHVnlB9sW5zZ-Xbc',
    appId: '1:528108806700:ios:4b84302bbf819afd69e789',
    messagingSenderId: '528108806700',
    projectId: 'sale-app-cf077',
    storageBucket: 'sale-app-cf077.firebasestorage.app',
    iosBundleId: 'com.anas.saleapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjrkWtBY4U_9sgJK5zHVnlB9sW5zZ-Xbc',
    appId: '1:528108806700:ios:4b84302bbf819afd69e789',
    messagingSenderId: '528108806700',
    projectId: 'sale-app-cf077',
    storageBucket: 'sale-app-cf077.firebasestorage.app',
    iosBundleId: 'com.anas.saleapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDk8qa0czd0vYTER7ZJ_Bq8gU_eBFgVHJY',
    appId: '1:528108806700:web:54c1064646dab66669e789',
    messagingSenderId: '528108806700',
    projectId: 'sale-app-cf077',
    authDomain: 'sale-app-cf077.firebaseapp.com',
    storageBucket: 'sale-app-cf077.firebasestorage.app',
    measurementId: 'G-G15CHHR7RN',
  );
}
